spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/learning-path?useSSL=false'
    username: 'root'
    password: 'TurabEybaliyev1998'
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
